// AUTO-GENERATED by scripts/gen-metafields.mjs. DO NOT EDIT.
//
// `npm run gen:metafields` を実行すると、Admin API のメタフィールド定義のうち
// Storefront から読める（access.storefront === "PUBLIC_READ"）スカラー型のものが
// ここに書き出される。
import type { MetafieldDef } from './metafields';

export const PRODUCT_METAFIELDS = [
  { namespace: "custom", key: "brand_name", label: "作家・ブランド名", type: "single_line_text_field" },
] as const satisfies readonly MetafieldDef[];

export const VARIANT_METAFIELDS = [
  { namespace: "custom", key: "size", label: "サイズ", type: "single_line_text_field" },
] as const satisfies readonly MetafieldDef[];
